#NAME - ID PROJECT
spring.application.name=api-rest-persona-jenkins

#PROPERTIES DATASOURCE
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=system
spring.datasource.password=Mauricio2003

#PROPERTIES HIBERNATE Y JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

#SERVER PORT APACHE TOMCAT
server.port=7575